# This is a basic workflow to help you get started with Actions

name: dev-deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  workflow_dispatch:
    branches: [ master ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: accessing remote dev YAC server and deploying.
        uses: fifsky/ssh-action@master
        with:
          command: |
            whoami
            cd ~/YAC
            git checkout master
            git fetch --all
            git reset origin/master --hard
            gogogo
          host: ${{ secrets.REMOTE_IP }}
          user: ${{ secrets.REMOTE_SSH_ID }}
          key: ${{ secrets.REMOTE_SSH_KEY}}

